# Generated by Django 5.0.7 on 2024-08-03 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('min_cpu', models.CharField(max_length=100)),
                ('min_gpu', models.CharField(max_length=100)),
                ('min_ram', models.IntegerField(help_text='Minimum RAM in GB')),
                ('min_storage', models.IntegerField(help_text='Minimum Storage in GB')),
                ('min_os_version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPCSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpu', models.CharField(max_length=100)),
                ('gpu', models.CharField(max_length=100)),
                ('ram', models.IntegerField(help_text='RAM in GB')),
                ('storage', models.IntegerField(help_text='Storage in GB')),
                ('os_version', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
